name: Generate ASCII

on: push

jobs:
  ascii_job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v4

     - name: Install Cowsay program
       run: sudo apt-get install cowsay -y
  
     - name: Exicute Cowsey command
       run: cowsay -f bird "Run for cover, I am a bird----RAWR" >> bird.txt

     - name: Test file exists
       run: grep -i "bird" bird.txt

     - name: TRead file
       run: cat bird.txt  

     - name: List repo files
       run: ls -ltra

    #  - name: Read file
    #    run: cat README.md 